### ISSUE TITLE
Missing translation key error

### ISSUE THREAD

**Issue by dcyriller** [jasonmit/ember-intl-cp-validations#45]
Hello @jasonmit, thank you for your work on `ember-intl`. It is very usefull :)

Using the latest npm-published version, we had a small error in console. A translation key was missing. Instead of getting a warning, we got a console error. It was related to https://github.com/ember-intl/cp-validations/pull/43

Full error is:
```
Assertion Failed: When calling `warn` you must provide an `options` hash as the third parameter.  `options` should include an `id` property.
```

The solution was to upgrade to the latest tagged version (`ember-intl-cp-validation: git+https://gitlab.qonto.co/ember-intl/cp-validations.git#v4.0.1`).

It's not very important but just wanted to let know. Maybe you could release the last version to npm?

**Comment by jasonmit** [comment]
Sorry for the confusion, this lib is now published under the scoped name `@ember-intl`.

`ember i @ember-intl/cp-validations` should pull in 4.0.1.  Remove `ember-intl-cp-validations` to avoid any conflicts of having both libs installed.

If this solves your issue, please close otherwise let me know :)

**Comment by dcyriller** [comment]
Yes, it does! It makes sense. Thank you for your answer :)
